### PR TITLE
Merge Ahmed brach

### PR DESCRIPTION
**Pull request by rlanzafame**
Hi @ahmedfarhatx22 I see you still have a branch open - is there anything important in here that needs to be added?

Note that since Mike merged his massive update the MR will not be automatic, which means it might be...tricky. See you you can use the GitHub tools to explore what the differences are. We can also try to resolve it on campus this week if you have the time

### CODE REVIEW

**Comment by rlanzafame** [comment]
as you can see above it looks like just a few riles. note that you can continue to work on this branch and add commits if there is still work to do. then when there are no conflicts it will be allowed to merge

**Comment by ahmedfarhatx22** [comment]
Hi Robert,
Nothing important needs to be added here just some review and some comments
that need to be removed from code. I will get everything ready and drop by
your office on thursday maybe?

Kind regards,
Ahmed

**Comment by mike-mendoza** [comment]
@ahmedfarhatx22 if there are minor comments you can talk directly with me. Send me a teams message (or mail) any time you want to discuss the changes.

**Comment by rlanzafame** [comment]
If you guys can take care of edits that would be great. But @ahmedfarhatx22 does your comment mean that there are no commits to be made? Is this MR needed, or not?

**Comment by ahmedfarhatx22** [comment]
What do you mean by MR? And its okay I can just work on the merged file
right? Then I do my edits there or isnt that possible?

**Comment by rlanzafame** [comment]
MR = Merge Request. BUt I think i understand now...it looks like all the commits listed above are just adding or replacing files, right? If so then i think i can merge this myself.

**Comment by ahmedfarhatx22** [comment]
Yes they are all added files!

**Comment by rlanzafame** [comment]
ok, i merge. see you on the other side!

**Pull request merged**
